cmd_drivers/gpu/pvr/refcount.o := arm-linux-gcc -Wp,-MD,drivers/gpu/pvr/.refcount.o.d  -nostdinc -isystem /opt/EmbedSky/4.4.6/lib/gcc/arm-embedsky-linux-gnueabi/4.4.6/include -I/home/andy/tq210/opt/EmbedSky/TQ210/Kernel_3.0.8_TQ210_for_Linux_v2.1/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-s5pv210/include -Iarch/arm/plat-s5p/include -Iarch/arm/plat-samsung/include -w -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Wdeclaration-after-statement -Wpointer-arith -Wmissing-format-attribute -Wno-format-zero-length -Wmissing-prototypes -Wstrict-prototypes -Wno-unused-parameter -Wno-sign-compare -Werror -fno-strict-aliasing -Wno-pointer-arith -Os -DLINUX -D__linux__ -DANDROID -Idrivers/gpu/pvr -DSUPPORT_SGX_NEW_STATUS_VALS -DSUPPORT_SGX_HWPERF -DSYS_USING_INTERRUPTS -DPVR_SECURE_HANDLES -DSUPPORT_DBGDRV_EVENT_OBJECTS -DTRANSFER_QUEUE -DSUPPORT_SGX -DLDM_PLATFORM -DPVR_LINUX_USING_WORKQUEUES -DPVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE -DPVR_LINUX_TIMERS_USING_WORKQUEUES -DSYS_CUSTOM_POWERLOCK_WRAP -DSUPPORT_MEMINFO_IDS -DSYS_SGX_ACTIVE_POWER_LATENCY_MS=100 -DPVR_BUILD_DATE="" -DPVRSRV_MODNAME="\"pvrsrvkm\"" -Idrivers/gpu/pvr/sgx -DSUPPORT_PERCONTEXT_PB -DSUPPORT_ACTIVE_POWER_MANAGEMENT -DSUPPORT_SGX_LOW_LATENCY_SCHEDULING -DPVR_NO_FULL_CACHE_OPS -DPVRSRV_NEED_PVR_DPF -DPVRSRV_NEED_PVR_ASSERT -DSUPPORT_HW_RECOVERY -DPVR_LDM_DRIVER_REGISTRATION_NAME="\"pvrsrvkm\"" -DPVR_BUILD_TYPE="\"release\"" -DRELEASE -DPVR_BUILD_DIR="\"smdkc110_android\"" -Idrivers/gpu/pvr/s5pc110 -DDISPLAY_CONTROLLER=s3c_lcd -DSLSI_S5PC110 -DSGX540 -DSUPPORT_SGX540 -DSGX_CORE_REV=120    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(refcount)"  -D"KBUILD_MODNAME=KBUILD_STR(pvrsrvkm)" -c -o drivers/gpu/pvr/refcount.o drivers/gpu/pvr/refcount.c

source_drivers/gpu/pvr/refcount.o := drivers/gpu/pvr/refcount.c

deps_drivers/gpu/pvr/refcount.o := \

drivers/gpu/pvr/refcount.o: $(deps_drivers/gpu/pvr/refcount.o)

$(deps_drivers/gpu/pvr/refcount.o):
